import { useState } from 'react'
import type { Category, Product, Subcategory } from './types'

const uid=()=>crypto.randomUUID()
const toDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})
const validWeight=(s:string)=>/^\d+(\.\d{1,3})?$/.test(s)&&Number(s)>0
type Props={categories:Category[];subcategories:Subcategory[];onProduct:(p:Product)=>Promise<void>;onCategory:(c:Category)=>Promise<void>;onSubcategory:(s:Subcategory)=>Promise<void>;notice:(s:string)=>void}

export function ProductEntry({categories,subcategories,onProduct}:Pick<Props,'categories'|'subcategories'|'onProduct'>){
 const [categoryId,setCategory]=useState(''),[sub,setSub]=useState(''),[error,setError]=useState('')
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),weight=String(f.get('weight')||''),file=f.get('image') as File,code=String(f.get('code')||'').trim().toUpperCase();if(!categoryId||!sub||!code||!validWeight(weight)||!file?.size){setError('Choose a category and subcategory, enter a valid design code and weight (up to 0.001 g), then select an image.');return};const image=await toDataUrl(file);await onProduct({id:uid(),designCode:code,categoryId,subcategoryId:sub,weightMg:Math.round(Number(weight)*1000),gridImage:image,detailImage:image,imageVersion:1,syncState:'PENDING_UPLOAD'});e.currentTarget.reset();setCategory('');setSub('');setError('')}
  return <form className="entry-form" onSubmit={e=>void submit(e)}><h2>Add one design</h2>{error&&<p className="field-error" role="alert">{error}</p>}<label>Design code<input name="code" required pattern="[A-Za-z0-9-]+" /></label><label>Category<select value={categoryId} onChange={e=>{setCategory(e.target.value);setSub('')}} required><option value="">Choose category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Subcategory<select value={sub} onChange={e=>setSub(e.target.value)} required disabled={!categoryId}><option value="">Choose subcategory</option>{subcategories.filter(x=>x.categoryId===categoryId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Weight in grams<input name="weight" inputMode="decimal" placeholder="12.345" required /></label><label>Image<input name="image" type="file" accept="image/*" required /></label><button className="primary">Stage design</button></form>
}

export function BatchEntry({categories,subcategories,onProduct}:Pick<Props,'categories'|'subcategories'|'onProduct'>){
 const [queue,setQueue]=useState<File[]>([]),[categoryId,setCategory]=useState(''),[sub,setSub]=useState(''),[code,setCode]=useState(''),[weight,setWeight]=useState(''),[error,setError]=useState('')
 const save=async()=>{const file=queue[0];if(!file||!categoryId||!sub||!code.trim()||!validWeight(weight)){setError('Complete the fixed category, subcategory, design code and weight for the active image.');return};const image=await toDataUrl(file);const designCode=code.trim().toUpperCase();await onProduct({id:uid(),designCode,categoryId,subcategoryId:sub,weightMg:Math.round(Number(weight)*1000),gridImage:image,detailImage:image,imageVersion:1,syncState:'PENDING_UPLOAD'});setQueue(q=>q.slice(1));setCode('');setWeight('');setError('')}
 return <section className="batch"><div><p className="eyebrow">queued image workflow</p><h2>Batch design entry</h2><p className="muted">The selected category and subcategory apply to the queue. Failed saves stay here until they succeed or you explicitly remove them.</p></div><div className="batch-layout"><label className="drop">Load images<input type="file" accept="image/*" multiple onChange={e=>setQueue(Array.from(e.target.files||[]))}/><strong>{queue.length} images queued</strong></label><div className="batch-form">{error&&<p className="field-error" role="alert">{error}</p>}<label>Category<select value={categoryId} onChange={e=>{setCategory(e.target.value);setSub('')}}><option value="">Choose category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Subcategory<select value={sub} disabled={!categoryId} onChange={e=>setSub(e.target.value)}><option value="">Choose subcategory</option>{subcategories.filter(x=>x.categoryId===categoryId).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Active design code<input value={code} onChange={e=>setCode(e.target.value)} disabled={!queue.length}/></label><label>Weight in grams<input value={weight} onChange={e=>setWeight(e.target.value)} disabled={!queue.length}/></label><button className="primary" disabled={!queue.length} onClick={()=>void save()}>Save active &amp; next</button></div></div><div className="queue">{queue.map((f,i)=><div className={i===0?'active':''} key={`${f.name}${i}`}><span>{i===0?'Active':'Queued'}</span>{f.name}<button className="quiet" onClick={()=>setQueue(q=>q.filter((_,index)=>index!==i))}>Remove</button></div>)}</div></section>
}

export function Taxonomy({categories,subcategories,onCategory,onSubcategory,notice}:Pick<Props,'categories'|'subcategories'|'onCategory'|'onSubcategory'|'notice'>){
 const addCategory=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')||'').trim();if(!name)return;if(categories.some(x=>x.name.toLowerCase()===name.toLowerCase())){notice('That category already exists.');return}await onCategory({id:uid(),name,active:true});e.currentTarget.reset();notice('Category added locally.')}
 const addSub=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),categoryId=String(f.get('category')||''),name=String(f.get('name')||'').trim();if(!categoryId||!name)return;if(subcategories.some(x=>x.categoryId===categoryId&&x.name.toLowerCase()===name.toLowerCase())){notice('That subcategory already exists in the selected category.');return}await onSubcategory({id:uid(),categoryId,name,active:true});e.currentTarget.reset();notice('Subcategory added locally.')}
 return <section className="taxonomy"><div><p className="eyebrow">classification</p><h1>Categories shape the catalogue.</h1><form onSubmit={e=>void addCategory(e)}><h2>Add category</h2><label>Name<input name="name" required/></label><button className="primary">Add category</button></form><form onSubmit={e=>void addSub(e)}><h2>Add subcategory</h2><label>Category<select name="category" required><option value="">Choose category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Name<input name="name" required/></label><button className="primary">Add subcategory</button></form></div><div className="taxonomy-list">{categories.map(c=><article key={c.id}><strong>{c.name}</strong>{subcategories.filter(s=>s.categoryId===c.id).map(s=><span key={s.id}>{s.name}</span>)}</article>)}</div></section>
}
