import type { Order } from './types'
const grams=(mg:number)=>(mg/1000).toFixed(3)
export async function generateOrderPdf(order: Order) {
  if (!order.orderNumber) throw new Error('An order number is required before PDF generation.')
  const { jsPDF } = await import('jspdf')
  const pdf=new jsPDF({unit:'mm',format:'a4'}); let y=18
  pdf.setFontSize(18); pdf.text('shine jewels',14,y); y+=8; pdf.setFontSize(10)
  pdf.text(`Order #${String(order.orderNumber).padStart(4,'0')}`,14,y); pdf.text(order.vendor.name,120,y); y+=5
  pdf.text(`${order.vendor.address}, ${order.vendor.city} · ${order.vendor.type}`,120,y); y+=10
  pdf.setFontSize(8); pdf.text('No.  Design        Weight     Qty   Remark',14,y); y+=5
  for(const item of order.items){ if(y>275){pdf.addPage();y=18}; pdf.text(`${item.serialNumber}.    ${item.designCode}     ${grams(item.weightMg)} g     ${item.quantity}     ${item.remark || '—'}`,14,y); y+=7 }
  const quantity=order.items.reduce((n,i)=>n+i.quantity,0), weight=order.items.reduce((n,i)=>n+i.weightMg*i.quantity,0)
  y+=4; pdf.setFontSize(10);pdf.text(`Total quantity: ${quantity}    Total weight: ${grams(weight)} g`,14,y);y+=8;pdf.setFontSize(8);pdf.text(`Generated by ${order.salesperson} · ${new Date(order.generatedAt || Date.now()).toLocaleString()}`,14,y)
  pdf.save(`${order.vendor.name.replace(/\s+/g,'_')}_${new Date().toLocaleDateString('en-GB').replace(/\//g,'-')}_${String(order.orderNumber).padStart(4,'0')}.pdf`)
}
