import { LocalSqlite } from './local-sqlite'
import type { Category, Order, Product, Session, Subcategory, Vendor } from './types'
export type PendingOperation={id:string;idempotency_key:string;entity_type:string;operation:string;payload:string;retry_count:number}
export interface CatalogueStorage { products():Promise<Product[]>;hasLocalReplica():Promise<boolean>;saveProduct(x:Product):Promise<void>;categories():Promise<Category[]>;saveCategory(x:Category):Promise<void>;subcategories():Promise<Subcategory[]>;saveSubcategory(x:Subcategory):Promise<void>;vendors():Promise<Vendor[]>;saveVendor(x:Vendor):Promise<void>;orders():Promise<Order[]>;saveOrder(x:Order):Promise<void>;session():Promise<Session|null>;saveSession(x:Session):Promise<void>;clearSession():Promise<void>;storageBytes():Promise<number>;syncCheckpoint():Promise<number>;setSyncCheckpoint(x:number):Promise<void>;pendingOperations():Promise<PendingOperation[]>;completeOperation(id:string,error?:string):Promise<void>;remapCategoryId(from:string,to:string):Promise<void>;remapSubcategoryId(from:string,to:string):Promise<void>;applyRemoteChange(x:{entityType:string;entityId:string;operation:string;payload:unknown}):Promise<void>;cacheRemoteImage(productId:string,representation:'grid'|'detail',url:string,version:number):Promise<void> }
class SqliteOpfsStorage implements CatalogueStorage {
 private db=new LocalSqlite();private ready=this.bootstrap()
 private async bootstrap(){await this.db.execute('CREATE TABLE IF NOT EXISTS local_entities(entity_type TEXT NOT NULL,id TEXT NOT NULL,payload TEXT NOT NULL,deleted INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(entity_type,id))');if(await this.db.checkpoint('storage_schema_version')!=='4'){await this.db.execute("DELETE FROM local_entities WHERE (entity_type='product' AND id IN ('p1','p2')) OR (entity_type='category' AND id='rings') OR (entity_type='subcategory' AND id='solitaire') OR (entity_type='vendor' AND id='v1')");const rows=await this.db.execute("SELECT id,payload FROM local_entities WHERE entity_type='product' AND deleted=0");for(const row of rows.rows||[]){const record=row as {id:string;payload:string},product=JSON.parse(record.payload) as Product;if(product.syncState==='SYNCED'&&product.gridImage===product.id+'-grid-v'+product.imageVersion)await this.db.execute("DELETE FROM local_entities WHERE entity_type='product' AND id=?",[record.id])}await this.db.setCheckpoint('storage_schema_version','4')}}
 private async save(type:string,id:string,value:unknown){await this.db.execute('INSERT INTO local_entities(entity_type,id,payload,deleted,updated_at) VALUES(?,?,?,0,CURRENT_TIMESTAMP) ON CONFLICT(entity_type,id) DO UPDATE SET payload=excluded.payload,deleted=0,updated_at=CURRENT_TIMESTAMP',[type,id,JSON.stringify(value)])}
 private async values<T>(type:string){await this.ready;const x=await this.db.execute('SELECT payload FROM local_entities WHERE entity_type=? AND deleted=0 ORDER BY updated_at',[type]);return(x.rows||[]).map(r=>JSON.parse((r as {payload:string}).payload) as T)}
 private async persistProduct(x:Product,queue:boolean){let gridImage=x.gridImage,detailImage=x.detailImage;const grid=`${x.id}-grid-v${x.imageVersion}`,detail=`${x.id}-detail-v${x.imageVersion}`;if(x.gridImage.startsWith('data:')){await this.db.putImage(grid,x.gridImage);gridImage=grid}if(x.detailImage.startsWith('data:')){await this.db.putImage(detail,x.detailImage);detailImage=detail}await this.save('product',x.id,{...x,gridImage,detailImage});if(queue)await this.db.queueOperation('product','UPSERT',{id:x.id})}
 async products(){
  const items=await this.values<Product>('product')
  return Promise.all(items.map(async item=>{
   const load=async(path:string,representation:'grid'|'detail')=>{
    try{return await this.db.getImage(path)}
    catch{
     const localPath=item.id+'-'+representation+'-v'+item.imageVersion
     if(path===localPath)return 'https://pub-ddd4389cc31a46b6b365e21911f96e1f.r2.dev/shine-jewels-demo/products/'+encodeURIComponent(item.id)+'/v'+item.imageVersion+'/'+representation
     return path
    }
   }
   return {...item,gridImage:await load(item.gridImage,'grid'),detailImage:await load(item.detailImage,'detail')}
  }))
 }
 async hasLocalReplica(){await this.ready;const result=await this.db.execute("SELECT COUNT(*) count FROM local_entities WHERE entity_type='product' AND deleted=0");return Number((result.rows?.[0] as {count:number}|undefined)?.count||0)>0}
 async categories(){return(await this.values<Category>('category')).filter(x=>x.active)} async subcategories(){return(await this.values<Subcategory>('subcategory')).filter(x=>x.active)} async vendors(){return(await this.values<Vendor>('vendor')).filter(x=>!x.deleted)} async orders(){return this.values<Order>('order')} async session(){return(await this.values<Session>('offline-authorization'))[0]||null}
 async saveCategory(x:Category){await this.ready;await this.save('category',x.id,x);await this.db.queueOperation('category','UPSERT',x)} async saveSubcategory(x:Subcategory){await this.ready;await this.save('subcategory',x.id,x);await this.db.queueOperation('subcategory','UPSERT',x)} async saveVendor(x:Vendor){await this.ready;await this.save('vendor',x.id,x);await this.db.queueOperation('vendor','UPSERT',x)} async saveProduct(x:Product){await this.ready;await this.persistProduct(x,true)} async saveOrder(x:Order){await this.ready;await this.save('order',x.id,x);await this.db.queueOperation('presentation','FINALIZE',x)}
 async saveSession(x:Session){await this.ready;await this.save('offline-authorization',x.userId,x);await this.db.setCheckpoint('offline_authorization_expires_at',x.offlineAuthorizationExpiresAt)} async clearSession(){await this.ready;await this.db.execute("UPDATE local_entities SET deleted=1,updated_at=CURRENT_TIMESTAMP WHERE entity_type='offline-authorization'")} async storageBytes(){await this.ready;const x=await this.db.execute('SELECT COALESCE(SUM(bytes),0) bytes FROM storage_accounting');return Number((x.rows?.[0] as {bytes:number}|undefined)?.bytes||0)}
 async syncCheckpoint(){await this.ready;return Number(await this.db.checkpoint('sync_checkpoint')||0)} async setSyncCheckpoint(x:number){await this.ready;await this.db.setCheckpoint('sync_checkpoint',String(x))} async pendingOperations(){await this.ready;return await this.db.pendingOperations() as PendingOperation[]} async completeOperation(id:string,error?:string){await this.ready;await this.db.operationState(id,error?'ERROR':'SYNCED',error)}
 async remapCategoryId(from:string,to:string){if(from===to)return;await this.ready;const category=(await this.values<Category>('category')).find(item=>item.id===from);if(category){await this.save('category',to,{...category,id:to});await this.db.execute('UPDATE local_entities SET deleted=1 WHERE entity_type=? AND id=?',['category',from])}for(const subcategory of await this.subcategories())if(subcategory.categoryId===from)await this.save('subcategory',subcategory.id,{...subcategory,categoryId:to});for(const product of await this.products())if(product.categoryId===from)await this.save('product',product.id,{...product,categoryId:to})}
 async remapSubcategoryId(from:string,to:string){if(from===to)return;await this.ready;const subcategory=(await this.subcategories()).find(item=>item.id===from);if(subcategory){await this.save('subcategory',to,{...subcategory,id:to});await this.db.execute('UPDATE local_entities SET deleted=1 WHERE entity_type=? AND id=?',['subcategory',from])}for(const product of await this.products())if(product.subcategoryId===from)await this.save('product',product.id,{...product,subcategoryId:to})}
 async applyRemoteChange(x:{entityType:string;entityId:string;operation:string;payload:unknown}){await this.ready;if(x.operation==='ARCHIVE'||x.operation==='DELETE'){await this.db.execute('UPDATE local_entities SET deleted=1,updated_at=CURRENT_TIMESTAMP WHERE entity_type=? AND id=?',[x.entityType,x.entityId]);return}const type=x.entityType==='presentation'?'order':x.entityType;const payload=x.payload as Record<string,unknown>;await this.save(type,x.entityId,{...payload,id:x.entityId})}
 async cacheRemoteImage(productId:string,representation:'grid'|'detail',url:string,version:number){const response=await fetch(url);if(!response.ok)throw new Error('Image recovery download failed.');const data=`data:${response.headers.get('content-type')||'application/octet-stream'};base64,${btoa(String.fromCharCode(...new Uint8Array(await response.arrayBuffer())))}`,path=`${productId}-${representation}-v${version}`;await this.db.putImage(path,data);const result=await this.db.execute('SELECT payload FROM local_entities WHERE entity_type=? AND id=?',['product',productId]),record=result.rows?.[0] as {payload:string}|undefined;if(record){const product=JSON.parse(record.payload) as Product;await this.save('product',productId,{...product,[representation==='grid'?'gridImage':'detailImage']:path})}}
}
export const storage:CatalogueStorage=new SqliteOpfsStorage()
