import { workerApi } from './api'
import { storage } from './storage'

type Change={sequence_number:number;entity_type:string;entity_id:string;operation:string;payload:string}
type Bootstrap={categories:Record<string,unknown>[];subcategories:Record<string,unknown>[];vendors:Record<string,unknown>[];products:Record<string,unknown>[];presentations:Record<string,unknown>[];checkpoint:number}
const r2=import.meta.env.VITE_R2_PUBLIC_BASE_URL?.replace(/\/$/,'')||'https://pub-ddd4389cc31a46b6b365e21911f96e1f.r2.dev'
const image=(key:unknown)=>`${r2}/${String(key).split('/').map(encodeURIComponent).join('/')}`
const product=(x:Record<string,unknown>)=>({id:String(x.id),designCode:String(x.design_code),categoryId:String(x.category_id),subcategoryId:String(x.subcategory_id),weightMg:Number(x.weight_mg),gridImage:image(x.grid_image_key),detailImage:image(x.detail_image_key),imageVersion:Number(x.image_version),syncState:'SYNCED' as const})
const category=(x:Record<string,unknown>)=>({id:String(x.id),name:String(x.name),active:!x.deleted_at&&Boolean(x.is_active)})
const subcategory=(x:Record<string,unknown>)=>({id:String(x.id),categoryId:String(x.category_id),name:String(x.name),active:!x.deleted_at&&Boolean(x.is_active)})
const vendor=(x:Record<string,unknown>)=>({id:String(x.id),name:String(x.name),address:String(x.address),city:String(x.city),type:String(x.type),deleted:Boolean(x.deleted_at)})
async function digest(data:string){const bytes=await (await fetch(data)).arrayBuffer();return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function directUpload(token:string,productId:string,representation:'grid'|'detail',source:string,version:number){const blob=await (await fetch(source)).blob(),checksum=await digest(source),grant=await workerApi<{key:string;headers:Record<string,string>;url:string;sizeBytes:number;checksum:string}>('/images/upload-authorizations',{method:'POST',token,body:{productId,representation,imageVersion:version,sizeBytes:blob.size,checksum,contentType:blob.type||'application/octet-stream'}});const response=await fetch(grant.url,{method:'PUT',headers:grant.headers,body:blob});if(!response.ok)throw new Error(`Direct ${representation} upload failed.`);await workerApi('/images/confirm',{method:'POST',token,body:{key:grant.key,sizeBytes:grant.sizeBytes,checksum:grant.checksum}});return {key:grant.key,sizeBytes:grant.sizeBytes,checksum:grant.checksum}}
async function push(token:string,operation:Awaited<ReturnType<typeof storage.pendingOperations>>[number]){const payload=JSON.parse(operation.payload) as Record<string,unknown>;if(operation.entity_type==='category')return workerApi('/categories',{method:'POST',token,body:payload});if(operation.entity_type==='subcategory')return workerApi('/subcategories',{method:'POST',token,body:payload});if(operation.entity_type==='vendor')return workerApi('/vendors',{method:'POST',token,body:payload});if(operation.entity_type==='presentation'){const order=payload as unknown as {id:string;vendor:{id:string};items:{productId:string;quantity:number;remark:string}[]};return workerApi('/orders',{method:'POST',token,body:{id:order.id,vendorId:order.vendor.id,items:order.items.map(item=>({productId:item.productId,quantity:item.quantity,remark:item.remark}))}})}if(operation.entity_type==='product'){const item=(await storage.products()).find(x=>x.id===payload.id);if(!item)throw new Error('Queued product no longer exists locally.');const [gridImage,detailImage]=await Promise.all([directUpload(token,item.id,'grid',item.gridImage,item.imageVersion),directUpload(token,item.id,'detail',item.detailImage,item.imageVersion)]);return workerApi('/products',{method:'POST',token,body:{id:item.id,designCode:item.designCode,categoryId:item.categoryId,subcategoryId:item.subcategoryId,weightMg:item.weightMg,gridImage,detailImage}})}throw new Error(`Unsupported queued operation: ${operation.entity_type}.`)}
export async function initialDownload(token:string){const data=await workerApi<Bootstrap>('/sync/bootstrap',{token});for(const x of data.categories)await storage.applyRemoteChange({entityType:'category',entityId:String(x.id),operation:x.deleted_at?'ARCHIVE':'CREATE',payload:category(x)});for(const x of data.subcategories)await storage.applyRemoteChange({entityType:'subcategory',entityId:String(x.id),operation:x.deleted_at?'ARCHIVE':'CREATE',payload:subcategory(x)});for(const x of data.vendors)await storage.applyRemoteChange({entityType:'vendor',entityId:String(x.id),operation:x.deleted_at?'ARCHIVE':'CREATE',payload:vendor(x)});for(const x of data.products)await storage.applyRemoteChange({entityType:'product',entityId:String(x.id),operation:x.deleted_at?'ARCHIVE':'CREATE',payload:product(x)});await storage.setSyncCheckpoint(data.checkpoint)}
export async function cloudImageStorageBytes(token:string){const data=await workerApi<Bootstrap>('/sync/bootstrap',{token});return data.products.filter(product=>!product.deleted_at).reduce((total,product)=>total+Number(product.grid_image_size_bytes||0)+Number(product.detail_image_size_bytes||0),0)}
function changePayload(change:Change){const x=JSON.parse(change.payload) as Record<string,unknown>;if(change.entity_type==='product'&&change.operation!=='ARCHIVE')return product({id:change.entity_id,design_code:x.designCode,category_id:x.categoryId,subcategory_id:x.subcategoryId,weight_mg:x.weightMg,grid_image_key:(x.gridImage as Record<string,unknown>).key,detail_image_key:(x.detailImage as Record<string,unknown>).key,image_version:1});if(change.entity_type==='category')return {id:change.entity_id,name:x.name,active:true};if(change.entity_type==='subcategory')return {id:change.entity_id,name:x.name,categoryId:x.categoryId,active:true};if(change.entity_type==='vendor')return {id:change.entity_id,name:x.name,address:x.address,city:x.city,type:x.type};return x}
export async function synchronize(token:string){if(!navigator.onLine)return {synced:false,reason:'offline'};for(const operation of await storage.pendingOperations()){try{await push(token,operation);await storage.completeOperation(operation.id)}catch(error){await storage.completeOperation(operation.id,error instanceof Error?error.message:'Sync failed')}}const after=await storage.syncCheckpoint(),changes=await workerApi<Change[]>(`/sync/changes?after=${after}`,{token});for(const change of changes){await storage.applyRemoteChange({entityType:change.entity_type,entityId:change.entity_id,operation:change.operation,payload:changePayload(change)});await storage.setSyncCheckpoint(change.sequence_number)}return {synced:true,changes:changes.length}}
